namespace: apps
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: Always
storageClassName: manual
env:
  LOG_LEVEL: "INFO"
  REST_SERVER_PORT: "8080"
  ENABLE_RTSP: "true"
  GST_DEBUG: "1"
  HTTPS: "false"
  RTSP_PORT: "8554"
  http_proxy:
  https_proxy:
  no_proxy: "intel.com,.intel.com,localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,192.168.49.2"
# yamllint disable-line rule:line-length
# Set to true if direct access to /dev is required (e.g., for GPU/NPU access without device plugins)
privileged_access_required: false
gpu:
# Set to true only when K8S GPU device plugin is installed and configured
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
npu:
# Set to true only when K8S NPU device plugin is installed and configured
  enabled: false
  count: 1
config:
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"
    ext:
      rest_api_port: "30007"
      rtsp_output_port: "30025"
images:
  dlstreamer_pipeline_server: intel/dlstreamer-pipeline-server:2025.2.0-ubuntu22
